# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4833ba5ab786aadb43a69969e47b5887607930bfb8c5507f11efba6173a5a63e58002144ca0e1a7a6726a0df06a8965e4014b27d300ba77f40e1ca26080eb51f

test:
  secret_key_base: 2db1d6c03cc40f6ac6f646befe721ac5b4e51ecfacf541026b946931ab966e1b7f3ebf92273e3f6de1c25e7054e80f93fe009bbbda06086cb1e5a112228d05f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
